language: node_js
node_js:
  - 14

os:
  - linux

jobs:
  include:
    - stage: Install
      script: yarn --frozen-lockfile
      skip_cleanup: true
    
    - stage: Lint
      script: yarn lintonly
      skip_cleanup: true
    
    - stage: Test
      script: yarn test
      skip_cleanup: true
    
    - stage: Build
      script: npm run build
      skip_cleanup: true
    
    - stage: Release & Deploy
      script:
        - echo "Not yet done"
      if: branch = main